name             'rails_app_server'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures rails_app_server'
long_description 'Installs/Configures rails_app_server'
version          '0.1.0'
